---
- name: Install Curl
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  become_flags: "-H -S"

  tasks:
    - name: Install Curl
      apt:
        name: curl
        state: present  # You can use "latest" for the latest version or "absent" for removal
      vars:
        ansible_become_pass: Ubun2@L0gin 
