---
      
- name: Install wget
  hosts: all
  become: yes
  become_user: su
  become_method: sudo
  

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'  # Adjust for other Linux distributions

    - name: Install wget package
      ansible.builtin.package:
        name: wget
        state: present
      vars:
        ansible_become_password: Ubun2@L0gin

