---
- name: Execute tasks with root privileges
  hosts: all
  become: yes
  become_user: admin
  vars:
    ansible_become_pass: "Ubun2@L0gin"  # Replace with your root password

  

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'  # Adjust for other Linux distributions

    - name: Install wget package
      ansible.builtin.package:
        name: wget
        state: present
      
