---
- name: Execute a command with sudo
  hosts: all
  become: yes
  become_method: su
  become_user: admin
 
  tasks:     
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present



