---
- name: Install Curl
  hosts: all
  become: yes  # To execute with sudo privileges
  become_method: sudo
  become_user: root
  become_flags: "-H -S"

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Curl
      apt:
        name: curl
        state: present  # Ensure that curl is present (installed)
        vars:
        ansible_become_pass: Ubun2@L0gin 

