---
- name: Execute a command with sudo
  hosts: all
  become: yes
  become_method: sudo
  become_user: admin
  tasks:
    - name: Include sudo password from sudo_password.yml
      include_vars:
        file: sudo_password.yml
        name: sudo_password_vars

    tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

      environment:
        ANSIBLE_BECOME_PASS: "{{ sudo_password_vars.sudo_password }}"
      register: command_output

    - name: Display command output
      debug:
        var: command_output.stdout

