---
- name: Run Application with sudo
  hosts: all  # Replace with your target host or group
  become: yes
  become_method: sudo
  become_user: admin
  tasks:
    - name: Run your application
      become: yes
      shell: "apt remove curl -y"
      ignore_errors: yes
      
