---
- name: Execute a command with sudo
  hosts: all
  become: true

 
  tasks:     
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present



