---
- hosts: all  # Replace with the target hosts or groups
  become: no  # Run tasks with sudo (root) privileges

  tasks:
    - name: Install the application
      snap:
        name: curl
        state: absent
