---
- name: Gather System Information
  hosts: all  # Replace with the target host where you want to gather information
  become: yes  # To execute with sudo privileges

  tasks:
    - name: Gather System Information
      command: "uname -a"
      register: system_info
      changed_when: false  # Prevent Ansible from reporting 'changed' when running this task

    - name: Display System Information
      debug:
        var: system_info.stdout_lines
