---
- hosts: all  # Replace with the target hosts or groups
 

  tasks:
    - name: Install the application
      become: yes  # Individual task level privilege escalation
      snap:
        name: curl
        state: absent
        
