---
- hosts: all  # Replace with the target hosts or groups
  become: yes  # Individual task level privilege escalation

  tasks:
    - name: Remove vim
      apt:
        name: vim
        state: absent
        become: yes  # Ensure this task runs with sudo privileges


    
