---
- hosts: all  # Replace with the target hosts or groups
 

  tasks:
    - name: Install the application
      become: yes  # Individual task level privilege escalation
      become_user: admin  # Optional: Specify the user to become (e.g., root)
      apt:
        name: curl
        state: absent
