---
- name: Install Curl
  hosts: all
  become: yes  # To execute with sudo privileges

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Curl
      apt:
        name: curl
        state: present  # Ensure that curl is present (installed)

    # You can add more tasks or handlers as needed

  handlers:
    - name: Restart Service
      service:
        name: curl
        state: restarted

