---
- hosts: all  # Replace with the target hosts or groups
  become: yes  # Individual task level privilege escalation

  tasks:
    - name: Install the application
      apt-get:
        name: curl
        state: absent
        
