---
- name: Run df -h command
  hosts: all
  tasks:
    - name: Execute df -h command
      command: free -h
      register: df_output

    - name: Display df -h output
      debug:
        var: df_output.stdout_lines
