---
- name: Run Ubuntu Terminal Commands
  hosts: all  # Replace with the target host or group of hosts

  tasks:
    - name: Execute ls command
      command: apt install curl  # Replace with your desired terminal command

  
