---
- name: Run Terminal Commands
  hosts: all  # Replace with the target host or group of hosts

  tasks:
    - name: Execute Command
      command: ansible all -m shell -a "top -n 1" -b  # Replace with your desired command
