---
- name: Run Ubuntu Terminal Commands
  hosts: all  # Replace with the target host or group of hosts

  tasks:
    - name: Execute  command
      command: sudo apt remove curl -y  # Replace with your desired terminal command

  
