---
- name: Run Ubuntu Terminal Commands
  hosts: all  # Replace with the target host or group of hosts

  tasks:
    - name: Execute  command
      command: sudo -S <<< "123" apt remove curl  # Replace with your desired terminal command

  
