---
- name: Run Ubuntu Terminal Commands
  hosts: all  # Replace with the target host or group of hosts

  tasks:
    - name: Execute ls command
      command: apt-get update  # Replace with your desired terminal command

    - name: Execute another command
      command: echo "Hello, Ansible!"  # Replace with another command
