---
- name: Run Ubuntu Terminal Commands
  hosts: all  # Replace with the target host or group of hosts

  tasks:
    - name: Execute ls command
      command: echo "Ubun2@L0gin" | sudo -S -u admin apt install curl  # Replace with your desired terminal command

  
